HeterogeneousTestAlpakaWrapperCudaAsync_EX_CUDA_DLINK_LIB:=HeterogeneousTestAlpakaWrapperCudaAsync_nv
HeterogeneousTestCUDADevice_EX_CUDA_DLINK_LIB:=HeterogeneousTestCUDADevice_nv
HeterogeneousTestCUDAKernel_EX_CUDA_DLINK_LIB:=HeterogeneousTestCUDAKernel_nv
HeterogeneousTestCUDAWrapper_EX_CUDA_DLINK_LIB:=HeterogeneousTestCUDAWrapper_nv
RecoTrackerLSTCoreCudaAsync_EX_CUDA_DLINK_LIB:=RecoTrackerLSTCoreCudaAsync_nv
